name: Generate JSON Files

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm init -y
          npm install --save-dev js-yaml

      - name: Setup GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Setup article branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Checkout article branch
          git fetch origin article
          git checkout -b article origin/article

      - name: Generate JSON files
        run: node scripts/generate-json.js

      - name: Commit and push if changed
        run: |
          git add index.json tags.json Articles/*
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update: Generate index.json and tags.json"
            git push origin article
          fi
